apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: inno
data:
  DB_NAME: "orderservice"
  DB_HOST: "order-postgres"
  DB_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  USER_SERVICE_NAME: "user-service"
  USER_SERVICE_URL: "http://user-service:8080"
  KEYCLOAK_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "Oauth"
  KEYCLOAK_CLIENT_ID: "auth-service-client"
  SERVER_PORT: "8083"
