apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: inno
data:
  DB_NAME: "keycloak"
  DB_HOST: "auth-postgres"
  DB_PORT: "5432"
  APP_NAME: "auth-service"
  KEYCLOAK_REALM: "Oauth"
  KEYCLOAK_CLIENT_ID: "auth-service-client"
  USER_SERVICE_NAME: "user-service"
  USER_SERVICE_URL: "http://user-service:8080"
