apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: inno
data:
  DB_NAME: "userservice"
  DB_HOST: "user-postgres"
  DB_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KEYCLOAK_REALM: "Oauth"
